# .github/workflows/deploy.yml

name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - volynskiy-business-site  # <--- твоя ветка автодеплоя (можешь поменять на нужную)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: volynskiy-business-site
          directory: ./
